⚠️ CONFLICT! Lineage pull request for: skeleton
cisagov/guacamole-composition pull request #64
Opened 2024-12-06 23:28 UTC by cisagovbot

# Lineage Pull Request: CONFLICT #

<img align="left" alt="Achtung!!!" width="100" src="https://raw.githubusercontent.com/cisagov/action-lineage/develop/src/achtung.gif">

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-docker.git`](https://github.com/cisagov/skeleton-docker.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

The `lineage/skeleton` branch has **one or more unresolved merge conflicts**
that you must resolve before merging this pull request!

## How to resolve the conflicts ##

1. Take ownership of this pull request by removing any other assignees.

1. Clone the repository locally, and reapply the merge:

    ```console
    git clone git@github.com:cisagov/guacamole-composition.git guacamole-composition
    cd guacamole-composition
    git remote add skeleton https://github.com/cisagov/skeleton-docker.git
    git remote set-url --push skeleton no_push
    git switch develop
    git switch --create lineage/skeleton --track origin/develop
    git pull skeleton HEAD
    git status
    ```

1. Review the changes displayed by the `status` command.  Fix any conflicts and
   possibly incorrect auto-merges.

1. After resolving each of the conflicts, `add` your changes to the
   branch, `commit`, and `push` your changes:

    ```console
    git add .github/CODEOWNERS .github/workflows/build.yml Dockerfile README.md docker-compose.yml src/version.txt tests/conftest.py tests/container_test.py 
    git commit
    git push --force --set-upstream origin lineage/skeleton
    ```

    Note that you may *append* to the default merge commit message
    that git creates for you, but *please do not delete the existing
    content*.  It provides useful information about the merge that is
    being performed.

1. Wait for all the automated tests to pass.

1. Confirm each item in the "Pre-approval checklist" below.

1. Remove any of the checklist items that do not apply.

1. Ensure every remaining checkbox has been checked.

1. Mark this draft pull request "Ready for review".

## ✅ Pre-approval checklist ##

Remove any of the following that do not apply. If you're unsure about
any of these, don't hesitate to ask. We're here to help!

- [ ] ✌️ The conflicts in this pull request have been resolved.
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

Remove any of the following that do not apply. These boxes should
remain unchecked until the pull request has been approved.

- [ ] Bump major, minor, patch, or pre-release version [as
      appropriate](https://semver.org/#semantic-versioning-specification-semver)
      via the `bump_version.sh` script *if* this repository is
      versioned *and* the changes in this PR [warrant a version
      bump](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api).
- [ ] Finalize version.

## ✅ Post-merge checklist ##

Remove any of the following that do not apply.

- [ ] Create a release.

---

> [!NOTE]
> You are seeing this because one of this repository's maintainers has
> configured [Lineage] to open pull requests.

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

2025-09-02 22:48 UTC, mcdonnnj commented on compose.yml
> +      - 127.0.0.1:80:8080/tcp
Since we add the protocol specification `/tcp` this string cannot be parsed as a sexagesimal number.

2025-09-03 13:33 UTC, dv4harr10 approved these changes

2025-09-03 13:41 UTC, jsf9k requested changes
I am requesting a couple of changes, which may require upstream skeleton PRs.

2025-09-03 13:41 UTC, jsf9k commented on .pre-commit-config.yaml
> +    rev: 1.7.10
This version of bandit should match that on line 127.

2025-09-03 13:41 UTC, jsf9k commented on tag.sh
This file should no longer be necessary since we now version all repos and always create releases or pre-releases.

2025-09-03 14:52 UTC, mcdonnnj commented on .pre-commit-config.yaml
> +    rev: 1.7.10
Yep that needs to be changed upstream.

2025-09-03 18:04 UTC, mcdonnnj commented on .pre-commit-config.yaml
> +    rev: 1.7.10
Please see https://github.com/cisagov/skeleton-docker/pull/246.

2025-09-03 18:06 UTC, mcdonnnj commented on tag.sh
I intend to leave this while I do testing around the new immutable release functionality. Do you mind if we revisit this at a later time? There's already a PR to remove the script in https://github.com/cisagov/skeleton-docker/pull/131 that has been blocked.

2025-09-03 18:23 UTC, dav3r approved these changes

2025-09-03 18:52 UTC, jsf9k commented on tag.sh
Sure, that is fine.  FWIW, @felddy has been testing immutable releases in his personal repos and has run into some gotchas.  You might want to confer with him.

2025-09-03 18:53 UTC, jsf9k approved these changes

2025-09-04 17:21 UTC, jsf9k approved these changes

2025-09-11 14:42 UTC, merged